//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class franchiser_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public franchiser_table()
        {
            this.matter_table = new HashSet<matter_table>();
        }
    
        public int franchiser_id { get; set; }
        public string franchiser_name { get; set; }
        public Nullable<int> franchiser_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matter_table> matter_table { get; set; }
    }
}
