//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Material_ManagementEntities : DbContext
    {
        public Material_ManagementEntities()
            : base("name=Material_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<franchiser_table> franchiser_table { get; set; }
        public virtual DbSet<manufacturer_table> manufacturer_table { get; set; }
        public virtual DbSet<matter_table> matter_table { get; set; }
        public virtual DbSet<product_type> product_type { get; set; }
        public virtual DbSet<the_winning_type> the_winning_type { get; set; }
    }
}
