//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class matter_table
    {
        public int matterid { get; set; }
        public string matter_name { get; set; }
        public string matter_code { get; set; }
        public Nullable<int> product_type_id { get; set; }
        public Nullable<int> the_winning_type_id { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public Nullable<decimal> Selling_price { get; set; }
        public Nullable<int> manufacturer_id { get; set; }
        public Nullable<int> franchiser_id { get; set; }
    
        public virtual franchiser_table franchiser_table { get; set; }
        public virtual manufacturer_table manufacturer_table { get; set; }
        public virtual product_type product_type { get; set; }
        public virtual the_winning_type the_winning_type { get; set; }
    }
}
